title:              Yeochan Youn Webpage
email:              yyoun5@wisc.edu
description:        Yeochan Youn's Webpage
author:             Yeochan Youn
baseurl:            "/YeochanYoun119.github.io"
url:                "https://YeochanYoun119.github.io"

# Social Profiles
twitter_username:   
github_username: YeochanYoun119
facebook_username:  
instagram_username:  
linkedin_username: Yeochan-Youn 

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
